### ISSUE TITLE
cvbs output 

### ISSUE THREAD

**Issue by km-coded** [laurb9/tiny_scope#26]
sometimes, the oled screen isn't enough and there are so many cheap 3,5" tft/lcd displays which can fit a arduino nano or pro mini inside and can be used as a small portable oscilloscope in the field (kwad testing, service, etc). Just a little thought!

**Comment by laurb9** [comment]
thanks for the suggestion! I looked a little bit into it, looks like the AVR is too slow to generate video signal with actual graphics while doing something else like signal acquisition that also requires precise timing.

regarding large displays, I saw a few SPI TFT displays that may be worth looking at.
